### PR TITLE
Add VoiceNext natives.

### PR DESCRIPTION
**Pull request by WamWooWam**
Considering there's no less than 8 people who've pointed this out on the D#+ Discord server alone, it makes sense to me to just, add the natives to this repo. It's not like it really makes a large amount of difference.

I understand that FFmpeg is rather large, and not exactly git friendly, but if that's a problem, I feel the need to ask why we're hosting FFmpeg anyway? Can we not just link to the more up to date and easier to maintain [official windows builds](https://ffmpeg.zeranoe.com/builds/)? Or even direct people to install via `choco`?

### CODE REVIEW

**Comment by Emzi0767** [comment]
Currently wontfix - we will be adding them at a later date.

**Comment by WamWooWam** [comment]
I'm aware of this, but that's been the stance for nearly two years now, I don't really understand why we can't just get on with it?
2 years ago

**Comment by Emzi0767** [comment]
Principally because I need to rebuild and update them for all the current and upcoming VNext changes.

**Comment by WamWooWam** [comment]
Ahhhh, aight, that's fair enough

**Pull request closed without merging**
